// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_Dawson.Models;

#nullable disable

namespace Mission6_Dawson.Migrations
{
    [DbContext(typeof(MovieCollectionContext))]
    [Migration("20240220214851_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Mission6_Dawson.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryType = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryType = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryType = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryType = "Television"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryType = "VHS"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryType = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryType = "Comedy"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryType = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("Mission6_Dawson.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Mission6_Dawson.Models.Movie", b =>
                {
                    b.HasOne("Mission6_Dawson.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
